language: php

php:
  - 5.3
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm install -g grunt-cli

script:
  - phpunit
  - grunt tests --verbose

notifications:
  email:
    on_success: never
