sudo: false

language: php

matrix:
  include:
    - php: 5.2
      env: WP_VERSION=latest WP_MULTISITE=0 WP_TRAVISCI=travis:phpunit
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 WP_TRAVISCI=travis:phpunit
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1 WP_TRAVISCI=travis:phpunit
    - php: 5.6
      env: WP_TRAVISCI=travis:js-tests
    - php: 5.6
      env: WP_TRAVISCI=travis:php-lint

cache:
  - composer
  - $HOME/.composer/cache
  - npm

before_script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpunit" ]] || [[ "$WP_TRAVISCI" == "travis:js-tests" ]]; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:php-lint" ]] || [[ "$WP_TRAVISCI" == "travis:js-tests" ]] ; then
        npm install -g grunt-cli
        npm install
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:php-lint" ]] ; then
        composer install
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpunit" ]] ; then
      phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:php-lint" ]] ; then
      grunt phpcs
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:js-tests" ]] ; then
      grunt jasmine
    fi

notifications:
  email:
    on_success: never
